package DAOException;

public enum DAOExceptionErrorType 
{
	NEW_CUSTOMER_FAILED,
	REMOVE_CUSTOMER_FAILED,
	UPDATE_CUSTOMER_FAILED,
	NEW_COMPANY_FAILED,
	REMOVE_COMPANY_FAILED,
	UPDATE_COMPANY_FAILED,
	NEW_COUPON_FAILED,
	REMOVE_COUPON_FAILED,
	UPDATE_COUPON_FAILED,
	NEW_COUPON_OBJECT_FAILED,
	CUSTOMER_DETAILS_FAILED_TO_RETRIEVE,
	COMPANY_DETAILS_FAILED_TO_RETRIEVE,
	COUPON_DETAILS_FAILED_TO_RETRIEVE,
	COMPLETED,
	MISSING_ARGUMENT,
	WRONG_ARGUMENT,
	NEW_CUSTOMER_COUPON_FAILED,
	ADMIN_FAIL_LOGIN,
	CONNECTION_CLOSED;
}
